#
# csse332 examplePrograms makefile
#

PUBLISH_SUB_DIR = examples

RAW = \
	Examples \
	AroundTheWorld \
	maketutorial \
	gdbtutorial \
	HelloWorld.c \
#	synch.c \

include ~/code/scripts/Makefile.class.csse
